name: notifier_42
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rounded_loading_button: ^2.0.9
  percent_indicator: ^4.0.0
  dio: ^4.0.4
  loading_animation_widget: ^1.0.0+3
  flutter_secure_storage: ^5.0.2
  fl_chart: ^0.45.0
  cool_dropdown: ^1.4.1
  flutter_staggered_animations: ^1.0.0
  searchable_listview: ^1.3.3
  provider: ^6.0.2
  salomon_bottom_bar: ^3.2.0
  switcher_button: ^0.0.4
  url_launcher: ^6.0.20
  flutter_web_auth: ^0.4.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/app_logo.jpeg
    - assets/images/cover.jpg
    - assets/images/profile_picture.jpeg
    - assets/images/blank_profile_picture.png
    - assets/images/not_found.png
    - assets/images/imac_image.png
    - assets/icons/lock_icon.png
    - assets/icons/broken_robot.png
    - assets/icons/black_hole.png
    - assets/icons/change_arrows.png
    - assets/icons/compass_icon.png
    - assets/icons/target_icon.png

  fonts:
    - family: weiss
      fonts:
        - asset: assets/fonts/WeissStd.otf
        - asset: assets/fonts/WeissStd-Bold.otf
          weight: 700
