name: swifty_companion
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rounded_loading_button: ^2.0.9
  flutter_animation_progress_bar: ^2.0.1
  percent_indicator: ^4.0.0
  dio: ^4.0.4
  loading_animation_widget: ^1.0.0+3
  blur: ^3.0.0
  connectivity_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/app_logo.jpeg
    - assets/images/cover.jpg
    - assets/images/profile_picture.jpeg
    - assets/icons/lock_icon.png

  fonts:
    - family: weiss
      fonts:
        - asset: assets/fonts/WeissStd.otf
        - asset: assets/fonts/WeissStd-Bold.otf
          weight: 700
