name: swifty_companion
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rounded_loading_button: ^2.0.9
  percent_indicator: ^4.0.0
  dio: ^4.0.4
  loading_animation_widget: ^1.0.0+3
  flutter_secure_storage: ^5.0.2
  fl_chart: ^0.45.0
  cool_dropdown: ^1.4.1
  water_drop_nav_bar: ^2.1.0+8
  carousel_slider: ^4.0.0
  flutter_staggered_animations: ^1.0.0
  searchable_listview: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/app_logo.jpeg
    - assets/images/cover.jpg
    - assets/images/profile_picture.jpeg
    - assets/icons/lock_icon.png
    - assets/icons/broken_robot.png
    - assets/images/blank_profile_picture.png

  fonts:
    - family: weiss
      fonts:
        - asset: assets/fonts/WeissStd.otf
        - asset: assets/fonts/WeissStd-Bold.otf
          weight: 700
